Repository TEAM-Tn1/NUGUNA_Client, pull requests merged in 2021-12, with the labels that each got.

#167 마이페이지 로그인 관련 예외처리
  src/assets/mypage/index.ts
  src/assets/mypage/login.svg
  src/assets/mypage/logout.svg
  src/assets/mypage/written_post.svg
  src/components/default/modal/modalTemplate/ModalTemplate.tsx
  src/components/mypage/Mypage.tsx
  src/components/mypage/style/index.ts
  src/components/userInfo/UserInfo.tsx
  src/components/userInfo/style/index.ts
  src/util/api/mypage/index.ts
  src/util/api/userInfo/index.ts
  src/util/axios/index.ts
Labels: bug, enhancement

#168 메인으로 이동하게 해주는 컴포넌트 생성
  src/components/home/Home.tsx
  src/components/home/index.ts
  src/components/index.ts
  src/route/MainRouter.tsx
Labels: enhancement

#170 166 noti exceptions
  src/components/header/Header.tsx
  src/components/header/style/index.ts
  src/components/main/Main.tsx
  src/components/notification/list/List.tsx
  src/util/api/main/index.ts
Labels: enhancement

#172 (#163) 채팅 오류 수정
  package-lock.json
  src/components/chatList/ChatListContent.tsx
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Header.tsx
  src/components/detailPost/DetailContent.tsx
  src/components/detailPost/PostDeleteModal.tsx
  src/container/chatList/ChatListContainer.tsx
  src/container/detailChat/DetailChatContainer.tsx
  src/container/writePost/WritePostContainer.tsx
  src/modules/reducer/detailChat/index.ts
  src/util/hooks/socket/useSocket.tsx
  yarn.lock
Labels: bug

#175 [FIX] count 0일 때 display none
  src/components/header/Header.tsx
Labels: enhancement

#177 (#174) 실시간 채팅
  src/components/detailChat/Chats.tsx
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Footer.tsx
  src/components/detailPost/DetailContent.tsx
  src/container/detailPost/DetailPostContainer.tsx
  src/modules/action/writePost/interface/index.ts
  src/modules/reducer/writerPost/index.ts
  src/util/hooks/socket/useSocket.tsx
Labels: bug

#179 (#178) 소켓 연결 401
  src/util/hooks/socket/useSocket.tsx
Labels: bug

#176 [FIX] cursor: pointer;
  src/components/notification/list/style/index.ts
  src/components/notification/style/index.ts
Labels: enhancement

#181 (#180) 로그인 안했을 때 게시물 작성 막기
  src/components/post/PostWriteModal.tsx
  src/container/post/PostContanier.tsx
  src/container/writePost/WritePostContainer.tsx
  src/modules/middleware/post/index.ts
Labels: bug

#183 (#182) 게시물 삭제
  src/components/detailPost/DetailPost.tsx
  src/components/detailPost/PostDeleteModal.tsx
  src/container/detailPost/DetailPostContainer.tsx
Labels: bug

#184 60 alarm fcm test
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/components/notification/Noti.tsx
Labels: enhancement

#186 [FIX] 공구 게시물 제대로 보이게 만들기
  src/components/main/Main.tsx
Labels: enhancement

#188 [FIX] 공구게시물 두개 받아오기
  src/components/main/Main.tsx
  src/util/api/main/index.ts
Labels: enhancement

#189 [FIX] 갑자기 고쳐짐 ㄷ
  src/util/api/main/index.ts
Labels: enhancement
