Repository TEAM-Tn1/NUGUNA_Client, pull requests merged in 2021-11, with the labels that each got.

#54 🔀 :: (#53) Base url 변경
  .env
  src/util/api/default/index.ts
Labels: invalid

#58 (#32) detail post redux api
  src/components/detailPost/DetailContent.tsx
  src/components/detailPost/DetailPost.tsx
  src/components/detailPost/DetailPostFooter.tsx
  src/components/detailPost/PostDeleteModal.tsx
  src/components/detailPost/PostImgSlider.tsx
  src/components/detailPost/style/index.ts
  src/constance/uri.ts
  src/container/detailPost/DetailPostContainer.tsx
  src/models/dto/response/detailPostResponse.ts
  src/modules/action/detailPost/index.ts
  src/modules/action/detailPost/interface/index.ts
  src/modules/middleware/detailPost/index.ts
  src/modules/middleware/index.ts
  src/modules/reducer/detailPost/index.ts
  src/modules/reducer/detailPost/interface/index.ts
  src/modules/reducer/index.ts
  src/util/api/detailPost/index.ts
  src/util/hooks/detailPost/index.ts
  src/util/hooks/detailPost/useDetailPost.tsx
Labels: enhancement

#59 (#33) post list redux api
  src/components/main/Main.tsx
  src/components/post/PostContent.tsx
  src/components/post/PostList.tsx
  src/components/post/style/index.ts
  src/container/post/PostContanier.tsx
  src/modules/action/post/index.ts
  src/modules/action/post/interface/index.ts
  src/modules/middleware/post/index.ts
  src/modules/reducer/post/index.ts
  src/util/api/post/index.ts
Labels: enhancement

#62 (#47) post write
  src/components/writePost/ExplainPost.tsx
  src/components/writePost/Picture.tsx
  src/components/writePost/PostInfo.tsx
  src/components/writePost/WritePost.tsx
  src/components/writePost/style/index.ts
  src/constance/writePost/index.ts
  src/container/writePost/WritePostContainer.tsx
  src/modules/action/writePost/index.ts
  src/modules/action/writePost/interface/index.ts
  src/modules/middleware/index.ts
  src/modules/middleware/writePost/index.ts
  src/modules/reducer/index.ts
  src/modules/reducer/writerPost/index.ts
  src/modules/reducer/writerPost/interface/index.ts
  src/util/api/writePost/index.ts
  src/util/hooks/writePost/index.ts
  src/util/hooks/writePost/useWritePost.tsx
Labels: enhancement

#64 (#63) modify post
  src/components/detailPost/DetailPost.tsx
  src/components/post/Post.tsx
  src/components/post/PostWriteModal.tsx
  src/components/post/style/index.ts
  src/components/writePost/ExplainPost.tsx
  src/components/writePost/Picture.tsx
  src/components/writePost/PostInfo.tsx
  src/components/writePost/WritePost.tsx
  src/constance/uri.ts
  src/constance/writePost/index.ts
  src/container/detailPost/DetailPostContainer.tsx
  src/container/writePost/WritePostContainer.tsx
  src/models/dto/response/detailPostResponse.ts
  src/modules/action/writePost/index.ts
  src/modules/action/writePost/interface/index.ts
  src/modules/middleware/writePost/index.ts
  src/modules/reducer/writerPost/index.ts
  src/modules/reducer/writerPost/interface/index.ts
  src/util/api/writePost/index.ts
  src/util/hooks/writePost/useWritePost.tsx
Labels: enhancement

#66 (#65) socket 연동
  package-lock.json
  package.json
  src/container/chatList/ChatListContainer.tsx
Labels: enhancement

#71 [ADD] 토큰 재발급 기능 구현
  src/components/information/Information.tsx
  src/util/axios/index.ts
Labels: enhancement

#76 🔀 :: (#72) CI 구축 및 CD Eslint disable
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: enhancement

#75 [ADD] module 추가
  package.json
  yarn.lock
Labels: enhancement

#70 30 carrot chat
  src/components/chatList/ChatList.tsx
  src/components/chatList/ChatListContent.tsx
  src/components/chatList/TradeChatList.tsx
  src/components/chatList/style/index.ts
  src/constance/uri.ts
  src/container/chatList/ChatListContainer.tsx
  src/models/dto/response/chatListResponse.ts
  src/modules/action/chatList/index.ts
  src/modules/action/chatList/interface/index.ts
  src/modules/middleware/chatList/index.ts
  src/modules/middleware/index.ts
  src/modules/reducer/chatList/index.ts
  src/modules/reducer/chatList/interface/index.ts
  src/modules/reducer/index.ts
  src/util/api/chatList/index.ts
  src/util/hooks/chatList/index.ts
  src/util/hooks/chatList/useChatList.ts
  yarn.lock
Labels: enhancement

#77 (#67) 공동구매 채팅 리스트
  src/components/chatList/ChatList.tsx
  src/components/chatList/ChatListContent.tsx
  src/components/chatList/GroupChatList.tsx
  src/components/chatList/TradeChatList.tsx
  src/constance/uri.ts
  src/modules/action/chatList/index.ts
  src/modules/action/chatList/interface/index.ts
  src/modules/middleware/chatList/index.ts
  src/modules/reducer/chatList/index.ts
  src/util/api/chatList/index.ts
Labels: enhancement

#85 57 admin list detail
  .env
  package-lock.json
  src/components/admin/postList/PostReport.tsx
  src/components/admin/postList/Suggestion.tsx
  src/components/admin/postList/UserReport.tsx
  src/components/admin/postList/frame/Frame.tsx
  src/components/admin/postList/list/List.tsx
  src/components/admin/postList/listDetail/ListDetail.tsx
  src/container/admin/list/ReportPostContainer.tsx
  src/container/admin/list/ReportUserContainer.tsx
  src/modules/action/admin/interface/index.ts
  src/modules/action/admin/list/index.ts
  src/modules/action/admin/listDetail/index.ts
  src/modules/middleware/admin/index.ts
  src/modules/middleware/admin/list/Question.ts
  src/modules/middleware/admin/list/ReportPost.ts
  src/modules/middleware/admin/list/ReportUser.ts
  src/modules/middleware/admin/list/index.ts
  src/modules/middleware/index.ts
  src/modules/reducer/admin/index.ts
  src/modules/reducer/admin/list/QuestionState.ts
  src/modules/reducer/admin/list/ReportPostState.ts
  src/modules/reducer/admin/list/ReportUserState.ts
  src/modules/reducer/admin/list/index.ts
  src/modules/reducer/index.ts
  src/util/api/admin/list.ts
  src/util/api/admin/listDescription.ts
  src/util/axios/index.ts
  src/util/hooks/admin/listQuestion.tsx
  src/util/hooks/admin/listReportPost.tsx
  src/util/hooks/admin/listReportUser.tsx
Labels: enhancement

#88 모든 방 구독
  src/components/chatList/ChatList.tsx
  src/container/chatList/ChatListContainer.tsx
  src/util/hooks/socket/useSocket.tsx
Labels: enhancement

#89 55 mypage interlock
  src/assets/modal/index.ts
  src/assets/modal/upload_icon.svg
  src/assets/mypage/index.ts
  src/components/default/modal/modalTemplate/ModalTemplate.tsx
  src/components/default/modal/modalTemplate/style/index.ts
  src/components/mypage/Mypage.tsx
  src/components/mypage/mypageOptions/modifyInfo/ModifyInfo.tsx
  src/components/userInfo/UserInfo.tsx
  src/constance/modifyInfo/index.ts
  src/util/api/mypage/index.ts
  src/util/api/userInfo/index.ts
Labels: enhancement

#90 61 question answer
  src/constance/uri.ts
  src/modules/action/admin/interface/index.ts
  src/modules/action/admin/listDetail/index.ts
  src/modules/reducer/admin/list/ReportPostState.ts
Labels: enhancement

#91 61 question answer
  src/components/admin/postList/list/List.tsx
  src/components/admin/postList/listDetail/Answer.tsx
  src/components/admin/postList/listDetail/ListDetail.tsx
  src/util/api/admin/answer.ts
  src/util/api/admin/list.ts
Labels: enhancement

#92 모든 방 구독 취소
  src/components/chatList/ChatList.tsx
  src/components/chatList/ChatListContent.tsx
  src/components/chatList/GroupChatList.tsx
  src/components/chatList/TradeChatList.tsx
  src/container/chatList/ChatListContainer.tsx
  src/route/MainRouter.tsx
  src/util/hooks/socket/useSocket.tsx
Labels: enhancement

#93 특정 방 구독
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Header.tsx
  src/components/detailChat/style/index.ts
  src/container/detailChat/DetailChatContainer.tsx
  src/route/MainRouter.tsx
Labels: enhancement

#94 특정 방 구독 취소
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Header.tsx
Labels: enhancement

#95 방 입장
  src/components/detailPost/DetailContent.tsx
  src/components/detailPost/DetailPost.tsx
  src/container/detailPost/DetailPostContainer.tsx
  src/modules/action/detailPost/index.ts
  src/modules/action/detailPost/interface/index.ts
  src/modules/reducer/detailPost/index.ts
  src/modules/reducer/detailPost/interface/index.ts
  src/route/MainRouter.tsx
  src/util/hooks/detailPost/useDetailPost.tsx
  src/util/hooks/socket/useSocket.tsx
Labels: enhancement

#99 96 post report
  src/components/default/modal/modalTemplate/ModalTemplate.tsx
  src/components/default/modal/modalTemplate/style/index.ts
  src/components/detailPost/DetailContent.tsx
  src/components/detailPost/DetailPost.tsx
  src/components/userInfo/UserInfo.tsx
Labels: enhancement

#98 방 나가기
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Footer.tsx
  src/components/detailPost/DetailContent.tsx
Labels: enhancement

#103 [ADD] 사용자 정보 클릭 시 프로필 페이지로 이동
  src/components/detailPost/DetailContent.tsx
  src/components/detailPost/style/index.ts
Labels: enhancement

#105 101 get user black day
  src/components/admin/postList/list/List.tsx
  src/components/admin/postList/listDetail/Answer.tsx
  src/components/admin/postList/listDetail/ListDetail.tsx
  src/util/api/admin/answer.ts
Labels: enhancement

#106 검색
  src/components/header/Header.tsx
  src/components/header/style/index.ts
  src/components/post/PostList.tsx
  src/components/search/Search.tsx
  src/components/search/style/index.ts
  src/constance/search/index.ts
  src/constance/uri.ts
  src/container/search/SearchContainer.tsx
  src/models/dto/response/searchResponse.ts
  src/modules/action/search/index.ts
  src/modules/action/search/interface/index.ts
  src/modules/middleware/index.ts
  src/modules/middleware/search/index.ts
  src/modules/reducer/index.ts
  src/modules/reducer/search/index.ts
  src/modules/reducer/search/interface/index.ts
  src/util/api/search/index.ts
  src/util/hooks/search/index.ts
  src/util/hooks/search/useSearch.tsx
Labels: enhancement

#107 102 modify user black date
  src/components/admin/postList/listDetail/Answer.tsx
  src/util/api/admin/answer.ts
Labels: enhancement

#115 [ADD] 본인 신고 에러 예외 처리 추가
  src/components/default/modal/modalTemplate/ModalTemplate.tsx
Labels: enhancement

#114 110 router modify
  src/components/index.ts
  src/route/MainRouter.tsx
Labels: enhancement

#119 118 info modify
  src/components/information/Information.tsx
  src/components/mypage/Mypage.tsx
  src/components/userInfo/UserInfo.tsx
Labels: enhancement

#120 108 main post
  src/components/main/Main.tsx
  src/components/post/PostContent.tsx
  src/util/api/main/index.ts
Labels: enhancement

#121 채팅 내용 가져오기
  src/components/detailChat/Chats.tsx
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/style/index.ts
  src/constance/uri.ts
  src/container/detailChat/DetailChatContainer.tsx
  src/models/dto/response/detailChatResponse.ts
  src/modules/action/detailChat/index.ts
  src/modules/action/detailChat/interface/index.ts
  src/modules/middleware/detailChat/index.ts
  src/modules/middleware/index.ts
  src/modules/reducer/detailChat/index.ts
  src/modules/reducer/detailChat/interface/index.ts
  src/modules/reducer/index.ts
  src/util/api/detailChat/index.ts
  src/util/hooks/detailChat/index.ts
  src/util/hooks/detailChat/useDetailChat.tsx
Labels: enhancement

#124 [FIX] 토큰 재발급이 401일 때만 auth페이지로 이동
  src/util/axios/index.ts
Labels: bug

#125 메세지 전송
  src/components/chatList/ChatListContent.tsx
  src/components/detailChat/Chats.tsx
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Footer.tsx
  src/components/detailChat/style/index.ts
  src/models/dto/response/detailChatResponse.ts
  src/modules/action/detailChat/index.ts
  src/modules/action/detailChat/interface/index.ts
  src/modules/reducer/detailChat/index.ts
  src/util/hooks/detailChat/useDetailChat.tsx
Labels: enhancement

#126 택배 왔어요~!
  src/components/detailChat/Footer.tsx
Labels: enhancement

#129 무한스크롤
  src/modules/reducer/post/index.ts
Labels: bug

#131 계좌번호 보여주기
  package.json
  src/components/detailChat/Chats.tsx
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Footer.tsx
  src/components/detailChat/style/index.ts
  src/constance/uri.ts
  src/models/dto/response/detailChatResponse.ts
  src/modules/action/detailChat/index.ts
  src/modules/action/detailChat/interface/index.ts
  src/modules/middleware/detailChat/index.ts
  src/modules/middleware/writePost/index.ts
  src/modules/reducer/detailChat/index.ts
  src/modules/reducer/detailChat/interface/index.ts
  src/util/api/detailChat/index.ts
Labels: enhancement

#132 122 get noti list
  .github/workflows/CI.yml
  src/components/notification/Noti.tsx
  src/components/notification/list/List.tsx
  src/util/api/notificate/index.ts
Labels: enhancement

#140 139 noti tag get
  src/components/notification/tagRegister/TagRegister.tsx
  src/util/api/notificate/index.ts
Labels: enhancement

#141 134 noti tag post
  src/components/notification/tagRegister/TagRegister.tsx
  src/components/notification/tagRegister/style/index.ts
  src/util/api/notificate/index.ts
Labels: enhancement

#142 138 noti tag delete
  src/components/notification/tagRegister/TagRegister.tsx
  src/components/notification/tagRegister/style/index.ts
  src/util/api/notificate/index.ts
Labels: enhancement

#144 143 noti count
  src/components/header/Header.tsx
  src/components/header/style/index.ts
  src/util/api/header/index.ts
Labels: enhancement

#145 137 noti check
  src/components/notification/Noti.tsx
  src/components/notification/list/List.tsx
  src/util/api/notificate/index.ts
Labels: enhancement

#148 146 get noti whether
  src/components/chatList/ChatList.tsx
  src/util/api/chatNoti/index.ts
Labels: enhancement

#151 137 noti check
  src/components/chatList/ChatList.tsx
  src/util/api/chatNoti/index.ts
Labels: enhancement

#153 [FIX] refresh 토큰 만료시 로컬스토리지 초기화
  src/util/axios/index.ts
Labels: bug

#154 (#150) chat info
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Header.tsx
  src/constance/uri.ts
  src/models/dto/response/detailChatResponse.ts
  src/modules/action/detailChat/index.ts
  src/modules/action/detailChat/interface/index.ts
  src/modules/middleware/detailChat/index.ts
  src/modules/reducer/detailChat/index.ts
  src/modules/reducer/detailChat/interface/index.ts
  src/util/api/detailChat/index.ts
Labels: enhancement

#156 (#155) 수정사항
  public/favicon.ico
  public/index.html
  src/components/chatList/ChatListContent.tsx
  src/components/detailChat/Chats.tsx
  src/components/detailChat/DetailChat.tsx
  src/components/detailChat/Footer.tsx
  src/components/detailChat/style/index.ts
  src/modules/middleware/index.ts
  src/modules/reducer/detailChat/index.ts
  src/modules/reducer/detailChat/interface/index.ts
Labels: bug

#157 136 answer detail
  src/components/notification/answerCheck/Answer.tsx
  src/components/notification/answerCheck/index.ts
  src/components/notification/list/List.tsx
  src/util/api/notificate/index.ts
Labels: enhancement

#158 130 get post of specfic user
  src/components/default/profile/optionsTemplate/style/index.ts
  src/components/header/style/index.ts
  src/components/mypage/mypageOptions/likedPost/LikedPost.tsx
  src/components/mypage/mypageOptions/likedPost/style/index.ts
  src/components/mypage/mypageOptions/modifyInfo/style/index.ts
  src/components/mypage/mypageOptions/writtenPost/WrittenPost.tsx
  src/components/mypage/mypageOptions/writtenPost/style/index.ts
  src/components/mypage/style/index.ts
  src/components/userInfo/UserInfo.tsx
  src/components/userInfo/style/index.ts
  src/util/api/mypage/index.ts
Labels: enhancement

#160 159 noti link
  src/components/header/Header.tsx
  src/components/header/style/index.ts
  src/components/notification/Noti.tsx
  src/components/notification/tagRegister/TagRegister.tsx
Labels: enhancement

#162 작성한 게시물 오류 수정
  .gitattributes
  package-lock.json
  src/components/mypage/mypageOptions/writtenPost/style/index.ts
Labels: bug
